name: Check IP Addresses

on:
  push:
    branches:
      - main  # Atau branch lain yang Anda gunakan
  workflow_dispatch:  # Menambahkan trigger untuk menjalankan secara manual

jobs:
  check_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download IP list
        run: |
          curl -O https://raw.githubusercontent.com/ymyuuu/IPDB/refs/heads/main/proxy.txt

      - name: Check each IP and collect geolocation
        id: check_ip
        run: |
          echo "IP Address (Country Code)" > geolocation.txt
          while IFS= read -r ip; do
            echo "Checking IP: $ip"
            response=$(curl -s "https://api.ip.sb/geoip/$ip")
            country_code=$(echo $response | jq -r '.country_code')
            echo "$ip ($country_code)" >> geolocation.txt
          done < proxy.txt

      - name: Upload geolocation artifact
        uses: actions/upload-artifact@v3
        with:
          name: geolocation
          path: geolocation.txt
