name: Check Proxy IPs

on:
  workflow_dispatch: # Memungkinkan untuk menjalankan workflow secara manual
  schedule:
    - cron: '0 * * * *' # Menjalankan setiap jam

jobs:
  check_ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Menggunakan versi terbaru dari checkout

    - name: Fetch Proxy List
      id: fetch_proxies
      run: |
        curl -s https://raw.githubusercontent.com/ymyuuu/IPDB/refs/heads/main/proxy.txt -o proxy.txt

    - name: Check IPs
      id: check_ips
      run: |
        echo 'results=[]' > results.json
        while read -r ip; do
            response=$(curl -s "https://p01--boiling-frame--kw6dd7bjv2nr.code.run/check?ip=$ip&host=speed.cloudflare.com&port=443&tls=true")
            # Validasi respons dan pastikan itu adalah JSON yang valid
            if echo "$response" | jq -e . >/dev/null 2>&1; then
                # Simpan hasil ke results.json tanpa colo
                result="{\"ip\":\"$ip\",\"result\":$response}"

                # Menyimpan hasil ke results.json
                if [[ $(cat results.json | jq '. | length') -gt 0 ]]; then
                    echo ",$result" >> results.json
                else
                    echo "$result" >> results.json
                fi
            else
                echo "Invalid response for IP $ip: $response"
            fi
        done < proxy.txt

        # Menutup array JSON
        echo ']' >> results.json

        # Membuat hasil JSON yang valid
        mv results.json tmp.json
        echo 'results=[' > results.json
        cat tmp.json >> results.json
        echo ']' >> results.json
        rm tmp.json

    - name: Upload Results
      uses: actions/upload-artifact@v3  # Menggunakan versi terbaru dari upload-artifact
      with:
        name: check-results
        path: results.json
